(() => {
  "use strict";
  const canvas=document.querySelector("#game-canvas"); if(!canvas)return; const ctx=canvas.getContext("2d");
  const status=document.querySelector("#game-status"),scoreEl=document.querySelector("#score"),livesEl=document.querySelector("#lives"),panel=document.querySelector("#game-over-panel"),overScore=document.querySelector("#game-over-score");
  const speedSelect=document.querySelector("#speed-select"),soundToggle=document.querySelector("#sound-toggle"),startButton=document.querySelector("#start-game"),pauseButton=document.querySelector("#pause-game"),restartButton=document.querySelector("#restart-game"),againButton=document.querySelector("#game-over-restart");
  const speeds={slow:18,normal:14,fast:10}; let width=0,height=0,scale=1,paddle,ball,bricks=[],score=0,lives=3,running=false,paused=false,gameOver=false,timer=null,soundOn=true,audio=null,input=0;
  const t=(key)=>window.PrimeJohnI18n?.t(key)||key;
  function resize(){const rect=canvas.getBoundingClientRect();scale=Math.min(2,window.devicePixelRatio||1);canvas.width=Math.max(320,Math.floor(rect.width*scale));canvas.height=Math.max(260,Math.floor(rect.height*scale));width=canvas.width/scale;height=canvas.height/scale;ctx.setTransform(scale,0,0,scale,0,0);if(paddle){paddle.y=height-36;paddle.x=Math.min(Math.max(paddle.x,0),width-paddle.w);ball.x=Math.min(Math.max(ball.x,ball.r),width-ball.r);ball.y=Math.min(Math.max(ball.y,ball.r),height-ball.r);}draw();}
  function setupBricks(){bricks=[];const rows=5,cols=10,gap=7,margin=18,brickW=(width-margin*2-gap*(cols-1))/cols,brickH=18;for(let row=0;row<rows;row+=1)for(let col=0;col<cols;col+=1)bricks.push({x:margin+col*(brickW+gap),y:38+row*(brickH+gap),w:brickW,h:brickH,row,alive:true});}
  function resetGame(){stopTimer();score=0;lives=3;running=false;paused=false;gameOver=false;input=0;paddle={w:Math.max(72,Math.min(128,width*.14)),h:12,x:width/2-Math.max(72,Math.min(128,width*.14))/2,y:height-36};ball={x:width/2,y:paddle.y-10,r:6,vx:3,vy:-3};setupBricks();scoreEl.textContent="0";livesEl.textContent="3";panel.hidden=true;pauseButton.disabled=true;pauseButton.textContent=t("game.pause");status.textContent=t("game.status.start");draw();}
  function start(){if(running&&!paused)return;if(gameOver)resetGame();running=true;paused=false;gameOver=false;panel.hidden=true;pauseButton.disabled=false;pauseButton.textContent=t("game.pause");status.textContent=t("game.status.play");startTimer();tone(520,.05,"sine");}
  function startTimer(){stopTimer();timer=setInterval(step,speeds[speedSelect.value]);}
  function stopTimer(){if(timer!==null){clearInterval(timer);timer=null;}}
  function togglePause(){if(!running||gameOver)return;if(paused){paused=false;pauseButton.textContent=t("game.pause");status.textContent=t("game.status.play");startTimer();tone(620,.05,"sine");}else{paused=true;pauseButton.textContent=t("game.resume");status.textContent=t("game.status.pause");stopTimer();tone(280,.05,"sine");}}
  function loseLife(){lives-=1;livesEl.textContent=String(lives);tone(180,.12,"sawtooth");if(lives<=0){finish(false);return;}ball={x:width/2,y:paddle.y-10,r:6,vx:3,vy:-3};status.textContent=`${t("game.lives")}: ${lives}`;}
  function finish(cleared){running=false;paused=false;gameOver=true;stopTimer();pauseButton.disabled=true;panel.hidden=false;overScore.textContent=`${t("game.score")}: ${score}`;status.textContent=cleared?t("game.status.clear"):t("game.status.over");tone(cleared?860:120,.18,cleared?"triangle":"sawtooth");draw();}
  function step(){if(!running||paused||gameOver)return;paddle.x+=input*7;paddle.x=Math.max(0,Math.min(width-paddle.w,paddle.x));ball.x+=ball.vx;ball.y+=ball.vy;if(ball.x-ball.r<0||ball.x+ball.r>width){ball.vx*=-1;ball.x=Math.max(ball.r,Math.min(width-ball.r,ball.x));tone(260,.025,"sine");}if(ball.y-ball.r<0){ball.vy=Math.abs(ball.vy);tone(260,.025,"sine");}if(ball.y+ball.r>=paddle.y&&ball.y+ball.r<=paddle.y+paddle.h+Math.abs(ball.vy)&&ball.x>=paddle.x&&ball.x<=paddle.x+paddle.w&&ball.vy>0){const hit=(ball.x-(paddle.x+paddle.w/2))/(paddle.w/2);ball.vx=hit*4;ball.vy=-Math.max(3,Math.abs(ball.vy));ball.y=paddle.y-ball.r;tone(520,.03,"sine");}if(ball.y-ball.r>height){loseLife();draw();return;}for(const brick of bricks){if(!brick.alive)continue;if(ball.x+ball.r>brick.x&&ball.x-ball.r<brick.x+brick.w&&ball.y+ball.r>brick.y&&ball.y-ball.r<brick.y+brick.h){brick.alive=false;score+=10;scoreEl.textContent=String(score);ball.vy*=-1;tone(760,.04,"triangle");break;}}if(bricks.every((brick)=>!brick.alive)){finish(true);return;}draw();}
  function draw(){ctx.fillStyle="#1b1412";ctx.fillRect(0,0,width,height);ctx.strokeStyle="rgba(255,192,120,.08)";for(let x=0;x<width;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,height);ctx.stroke();}for(let y=0;y<height;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(width,y);ctx.stroke();}bricks.forEach((brick)=>{if(!brick.alive)return;ctx.fillStyle=["#ffc078","#f6ad7b","#ff9f9f","#d9a7ff","#9ed8ff"][brick.row];ctx.fillRect(brick.x,brick.y,brick.w,brick.h);});ctx.fillStyle="#fff4e8";ctx.fillRect(paddle.x,paddle.y,paddle.w,paddle.h);ctx.beginPath();ctx.arc(ball.x,ball.y,ball.r,0,Math.PI*2);ctx.fillStyle="#ffd166";ctx.fill();}
  function tone(frequency,duration,type){if(!soundOn)return;const AudioCtor=window.AudioContext||window.webkitAudioContext;if(!AudioCtor)return;audio=audio||new AudioCtor();if(audio.state==="suspended")audio.resume();const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.type=type;oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.035,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);oscillator.connect(gain);gain.connect(audio.destination);oscillator.start();oscillator.stop(audio.currentTime+duration);}
  function setInput(value){input=value;}
  const keyMap={ArrowLeft:-1,a:-1,A:-1,ArrowRight:1,d:1,D:1};window.addEventListener("keydown",(event)=>{if(keyMap[event.key]!==undefined){event.preventDefault();setInput(keyMap[event.key]);}if(event.key===" "){event.preventDefault();togglePause();}});window.addEventListener("keyup",(event)=>{if(keyMap[event.key]!==undefined)setInput(0);});window.addEventListener("resize",resize);
  document.querySelectorAll("[data-direction]").forEach((button)=>{button.addEventListener("pointerdown",(event)=>{event.preventDefault();setInput(button.dataset.direction==="left"?-1:1);canvas.focus();});button.addEventListener("pointerup",()=>setInput(0));button.addEventListener("pointerleave",()=>setInput(0));});
  startButton.addEventListener("click",start);againButton.addEventListener("click",()=>{resetGame();start();});restartButton.addEventListener("click",()=>{resetGame();start();});pauseButton.addEventListener("click",togglePause);soundToggle.addEventListener("click",()=>{soundOn=!soundOn;soundToggle.textContent=t(soundOn?"game.sound.on":"game.sound.off");soundToggle.setAttribute("aria-pressed",String(soundOn));if(soundOn)tone(620,.05,"sine");});speedSelect.addEventListener("change",()=>{if(running&&!paused)startTimer();});window.addEventListener("languagechange",()=>{if(!running&&!gameOver)status.textContent=t("game.status.start");pauseButton.textContent=paused?t("game.resume"):t("game.pause");soundToggle.textContent=t(soundOn?"game.sound.on":"game.sound.off");});
  resize();resetGame();
})();
